### ISSUE TITLE
VPN mounting can fail without notification

### ISSUE THREAD

**Issue by petit42** [labriqueinternet/vpnclient_ynh#7]
Even though the VPN is down, the specific ssid remains available. Then, I can be connected to Internet, without notice that the connection is not secured. In such a case,  wouldn't it be good idea to not supply the ssid, to avoid any risk of not secured connection (same for app TOR) ?

**Comment by jvaubourg** [comment]
Once the Hotspot app is started on the system, this one becomes a router because the forwarding options are set. So, any configured AP in Hotspot allows the clients to communicate on the internet if the wired interface has a default route to the internet.

Installing the VPN Client app (almost) changes the default route on the system. So, with this app, any AP configured in Hotspot offers a connection to the Internet through a VPN. If the VPN service is started but the tunnel is not correctly mounted, the default behavior applies and the client can use the internet connection without a secure tunnel.

The Tor Client app has a different behavior. it does not change the default route but add a PREROUTING rule on its interface and redirects all traffic to an internal socket. Then, the Tor traffic is routed via the VPN if the VPN is active or directly via the internet connection in the opposite case. If the Tor service is not started, the user can directly use the internet connection without anonymity. If the service is started but the Tor tunnel failed to mount (the socket is not created but the PREROUTING rule is set), the client will not be able to use any internet connection.

I agree with you, a client connected thanks to a "VPN Wifi AP" or a "Tor Wifi AP" should not be able to use an internet connection if the VPN or the Tor service is not functional. We need to find a workaround, and this probably implies to use netns for having self-contained routing tables and forwarding rules among apps that depend on Hotspot.

**Comment by jvaubourg** [comment]
This issue was solved with firewalling and a systemd restart on-failure service.

* Nothing can go out through the wired interface, except the connection establishment with the VPN server
* When the VPN is down, wifi clients no longer have access to the Internet
* If OpenVPN fails, it retries infinitely
* In addition, the self-hosted services are now only accessible from the VPN and not directly from the wired interface (except for local networks)

**Warning:** the firewalling will be active only with YunoHost-Moulinette >= 2.4.0. And Moulinette 2.4.0 will be available as soon as possible ;).
